import React, { useState, useEffect, useRef } from 'react';
import Editor from '@monaco-editor/react';
import { executePythonCode, generateCopilotCode, saveSandboxCode, getSandboxCode } from '../../api/api';
import toast from 'react-hot-toast';
import { useData } from '../../context/DataContext';

export default function NotebookPage() {
  const { sessionId } = useData();

  const [code, setCode] = useState(`# StatsFlow Python Sandbox
# ------------------------
# Write any Python code here.

import pandas as pd
import matplotlib.pyplot as plt

# If you have uploaded and cleaned a dataset, it is available as 'df'!
# Example:
# print("Dataset Shape:", df.shape)
# print("\\nFirst 5 rows:")
# print(df.head())
    
# Plot example:
# df.select_dtypes(include='number').iloc[:, 0].plot(kind='hist')
# plt.title('Distribution of First Numeric Column')
# plt.show()
`);

  const [output, setOutput] = useState(null);
  const [error, setError] = useState(null);
  const [figures, setFigures] = useState([]);
  const [isRunning, setIsRunning] = useState(false);

  // Copilot state
  const [copilotPrompt, setCopilotPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  // Layout states for side-by-side
  const [editorWidth, setEditorWidth] = useState(50); // percentage
  const [isResizing, setIsResizing] = useState(false);
  const containerRef = useRef(null);

  const handleMouseDown = (e) => {
    e.preventDefault();
    setIsResizing(true);
  };

  useEffect(() => {
    const fetchCode = async () => {
      if (!sessionId) return;
      try {
        const res = await getSandboxCode(sessionId);
        if (res.success && res.code) {
          setCode(res.code);
        }
      } catch (err) {
        console.error("Failed to load saved notebook code:", err);
      }
    };
    fetchCode();
  }, [sessionId]);

  useEffect(() => {
    const handleMouseMove = (e) => {
      if (!isResizing || !containerRef.current) return;
      
      const containerRect = containerRef.current.getBoundingClientRect();
      let newWidth = ((e.clientX - containerRect.left) / containerRect.width) * 100;
      
      // Constrain between 20% and 80%
      if (newWidth < 20) newWidth = 20;
      if (newWidth > 80) newWidth = 80;
      
      setEditorWidth(newWidth);
    };

    const handleMouseUp = () => {
      setIsResizing(false);
    };

    if (isResizing) {
      document.addEventListener('mousemove', handleMouseMove);
      document.addEventListener('mouseup', handleMouseUp);
      document.body.style.cursor = 'col-resize';
      document.body.style.userSelect = 'none';
    } else {
      document.body.style.cursor = 'default';
      document.body.style.userSelect = 'auto';
    }

    return () => {
      document.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('mouseup', handleMouseUp);
      document.body.style.cursor = 'default';
      document.body.style.userSelect = 'auto';
    };
  }, [isResizing]);

  const handleRun = async () => {
    setIsRunning(true);
    setOutput(null);
    setError(null);
    setFigures([]);
    
    const tid = toast.loading('Running Python code...');
    try {
      const res = await executePythonCode(sessionId, code);
      if (res.success) {
        setOutput(res.stdout);
        setError(res.stderr);
        setFigures(res.figures || []);
        toast.success('Execution completed!', { id: tid });
      }
    } catch (err) {
      toast.error('Execution failed.', { id: tid });
      setError(err.response?.data?.detail || err.message);
    } finally {
      setIsRunning(false);
    }
  };

  const handleCopilotGenerate = async () => {
    if (!copilotPrompt.trim()) return;
    setIsGenerating(true);
    const tid = toast.loading('Generating code...');
    try {
      const res = await generateCopilotCode(sessionId, copilotPrompt, code);
      if (res.success) {
        setCode(code + `\n\n# Generated by AI: ${copilotPrompt}\n${res.code}`);
        setCopilotPrompt('');
        toast.success('Code generated!', { id: tid });
      }
    } catch (err) {
      toast.error(err.response?.data?.detail || err.message, { id: tid });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSave = async () => {
    if (!sessionId) {
      toast.error('No active dataset session to save code to.', { icon: '⚠️' });
      return;
    }
    const tid = toast.loading('Saving code...');
    try {
      await saveSandboxCode(sessionId, code);
      toast.success('Code saved to database!', { id: tid, icon: '💾' });
    } catch (err) {
      toast.error('Failed to save code.', { id: tid });
      console.error(err);
    }
  };

  const handleEditorDidMount = (editor, monaco) => {
    editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyS, () => {
      handleSave();
    });
  };

  return (
    <div style={{ padding: '20px', height: 'calc(100vh - 80px)', display: 'flex', flexDirection: 'column' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
        <div>
          <h2 style={{ margin: 0, color: '#0f172a', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span style={{ fontSize: '24px' }}>🐍</span> Python Sandbox
          </h2>
          <p style={{ margin: '4px 0 0 0', color: '#64748b', fontSize: '14px' }}>
            Write and execute Python code instantly. {sessionId ? "Your active dataset is pre-loaded as 'df'." : "No active dataset loaded."}
          </p>
        </div>
        <div style={{ display: 'flex', gap: '12px' }}>
          <button 
            onClick={handleSave}
            style={{
              padding: '10px 16px',
              backgroundColor: '#3b82f6',
              color: '#fff',
              border: 'none',
              borderRadius: '8px',
              fontWeight: 700,
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              boxShadow: '0 4px 6px -1px rgba(59, 130, 246, 0.2)'
            }}
            title="Save Code (Ctrl+S)"
          >
            💾 Save
          </button>
          <button 
            onClick={handleRun}
            disabled={isRunning}
            style={{
              padding: '10px 24px',
              backgroundColor: '#10b981',
              color: '#fff',
              border: 'none',
              borderRadius: '8px',
              fontWeight: 700,
              cursor: isRunning ? 'not-allowed' : 'pointer',
              opacity: isRunning ? 0.7 : 1,
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              boxShadow: '0 4px 6px -1px rgba(16, 185, 129, 0.2)'
            }}
          >
            {isRunning ? 'Running...' : '▶ Run Code'}
          </button>
        </div>
      </div>

      <div ref={containerRef} style={{ display: 'flex', flex: 1, overflow: 'hidden' }}>
        {/* Left: Editor */}
        <div style={{ flex: `0 0 calc(${editorWidth}% - 8px)`, backgroundColor: '#1e1e1e', borderRadius: '12px', border: '1px solid #cbd5e1', overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
          <div style={{ padding: '8px 16px', backgroundColor: '#2d2d2d', color: '#fff', fontSize: '12px', fontWeight: 600, borderBottom: '1px solid #404040' }}>
            script.py
          </div>
          <div style={{ backgroundColor: '#1e1e1e', padding: '8px 16px', borderBottom: '1px solid #404040', display: 'flex', gap: '8px' }}>
            <input 
              type="text" 
              placeholder="✨ Ask AI Copilot to write code... (e.g. 'Plot the distribution of sales')" 
              value={copilotPrompt}
              onChange={e => setCopilotPrompt(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && handleCopilotGenerate()}
              style={{ flex: 1, backgroundColor: '#2d2d2d', color: '#fff', border: '1px solid #404040', borderRadius: '4px', padding: '6px 12px', fontSize: '13px', outline: 'none' }}
              disabled={isGenerating}
            />
            <button 
              onClick={handleCopilotGenerate}
              disabled={isGenerating || !copilotPrompt.trim()}
              style={{ backgroundColor: '#6366f1', color: '#fff', border: 'none', borderRadius: '4px', padding: '0 12px', fontSize: '13px', fontWeight: 600, cursor: isGenerating ? 'not-allowed' : 'pointer', opacity: isGenerating || !copilotPrompt.trim() ? 0.6 : 1 }}
            >
              {isGenerating ? 'Generating...' : 'Generate'}
            </button>
          </div>
          <div style={{ flex: 1, position: 'relative' }}>
            <Editor
              defaultLanguage="python"
              theme="vs-dark"
              value={code}
              onChange={(val) => setCode(val)}
              onMount={handleEditorDidMount}
              options={{
                minimap: { enabled: false },
                fontSize: 14,
                fontFamily: "'Fira Code', 'Cascadia Code', Consolas, monospace",
                scrollBeyondLastLine: false,
                smoothScrolling: true,
                padding: { top: 16 }
              }}
            />
          </div>
        </div>

        {/* Resizer Handle */}
        <div 
          onMouseDown={handleMouseDown}
          style={{ 
            width: '16px', 
            cursor: 'col-resize', 
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            zIndex: 10,
            margin: '0',
          }}
          title="Drag to resize"
        >
          {/* Visual dots or bar for the handle */}
          <div style={{ 
            width: '4px', 
            height: '40px', 
            backgroundColor: isResizing ? '#3b82f6' : '#cbd5e1', 
            borderRadius: '2px',
            transition: 'background-color 0.2s'
          }} />
        </div>

        {/* Right: Output */}
        <div style={{ flex: 1, backgroundColor: '#f8fafc', borderRadius: '12px', border: '1px solid #cbd5e1', overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
          <div style={{ padding: '8px 16px', backgroundColor: '#e2e8f0', color: '#334155', fontSize: '12px', fontWeight: 600, borderBottom: '1px solid #cbd5e1' }}>
            Terminal Output
          </div>
          <div style={{ flex: 1, padding: '16px', overflowY: 'auto', fontFamily: 'Consolas, monospace', fontSize: '13px' }}>
            {(!output && !error && figures.length === 0) ? (
              <div style={{ color: '#94a3b8', fontStyle: 'italic' }}>Waiting for execution...</div>
            ) : (
              <>
                {output && (
                  <pre style={{ margin: 0, whiteSpace: 'pre-wrap', color: '#334155' }}>
                    {output}
                  </pre>
                )}
                
                {error && (
                  <pre style={{ margin: output ? '16px 0 0 0' : 0, whiteSpace: 'pre-wrap', color: '#ef4444' }}>
                    {error}
                  </pre>
                )}

                {figures.length > 0 && (
                  <div style={{ marginTop: '24px', display: 'flex', flexWrap: 'wrap', gap: '16px', borderTop: '1px dashed #cbd5e1', paddingTop: '16px' }}>
                    {figures.map((b64, idx) => (
                      <div key={idx} style={{ backgroundColor: '#fff', padding: '12px', borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)', border: '1px solid #e2e8f0' }}>
                        <img src={`data:image/png;base64,${b64}`} alt={`Plot ${idx + 1}`} style={{ maxWidth: '100%', height: 'auto', display: 'block' }} />
                      </div>
                    ))}
                  </div>
                )}
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
